swagger: "2.0"
info:
  title: My API
  description: A simple REST API
  version: 1.0.0
paths:
  /users:
    get:
      description: Get all users
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
